Exception occurs while performing test_runs_001 